version: '3.8'
volumes:
  postgres_data:
  main_app_data:
services:
  postgres:
    image: 'postgres:13'
    ports:
      - '6500:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    restart: always

  main-app:
    build:
      context: .
      dockerfile: main-app/Dockerfile
    ports:
      - '4100:4100' # Map the port from the container to your host
    environment:
      - NODE_ENV=production
    restart: always
